[package]
name = "rdm4-bin"
version = "0.1.0"
authors = ["lukts30 <llukas21307@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
rdm4lib = { path = "rdm4lib" }
log = "0.4"
env_logger = "0.7.1"