on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: true

      - name: Package
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install libarchive-tools
          mkdir package
          ls -lah
          bsdtar -caf ./package/rdm4-windows-x64.zip rdm4-windows-x64
          bsdtar -caf ./package/rdm4-linux-x64.zip rdm4-linux-x64

      - name: Upload rdm4-windows-x64
        id: upload-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/rdm4-windows-x64.zip
          asset_name: rdm4-windows-x64.zip
          asset_content_type: application/zip

      - name: Upload rdm4-linux-x64
        id: upload-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/rdm4-linux-x64.zip
          asset_name: rdm4-linux-x64.zip
          asset_content_type: application/zip
